### ISSUE TITLE
Manager starts worker before calling run

### ISSUE THREAD

**Issue by lfportal** [shirren/bifrost#5]
When I run the manager example:
```ruby
manager = Bifrost::Manager.new
manager.add('topic_name', 'subscriber_name', proc { |m| puts "Received: message #{m}" })
manager.run
```
The worker starts immediately after calling `manager.add`. Also the worker dies immediately:

```
2.2.4 :002 > require 'bifrost'
 => true 
2.2.4 :003 > manager = Bifrost::Manager.new
 => #<Celluloid::Proxy::Cell(Bifrost::Manager:0x3ff41d10b14c)> 
2.2.4 :004 > manager.add('feedback-create', 'phoenix', proc {|m| pust m})
I, [2016-11-13T15:16:35.933570 #72206]  INFO -- : Worker feedback-createphoenix starting up...
I, [2016-11-13T15:16:35.934617 #72206]  INFO -- : Worker bootstrapping with ["worker_ready", "feedback-create", "phoenix"]...
 => #<Celluloid::Proxy::Cell(Celluloid::Supervision...
2.2.4 :005 > I, [2016-11-13T15:16:37.939651 #72206]  INFO -- : Worker feedback-createphoenix running...
E, [2016-11-13T15:16:37.948206 #72206] ERROR -- : Actor crashed!
TypeError: no implicit conversion of nil into String
	/Users/cake/.rvm/gems/ruby-2.2.4@os-bifrost/gems/azure-core-0.1.5/lib/azure/core/auth/signer.rb:44:in `digest'
	/Users/cake/.rvm/gems/ruby-2.2.4@os-bifrost/gems/azure-core-0.1.5/lib/azure/core/auth/signer.rb:44:in `sign'
	/Users/cake/.rvm/gems/ruby-2.2.4@os-bifrost/gems/azure-0.7.6/lib/azure/service_bus/auth/shared_access_signer.rb:39:in `signature'
	/Users/cake/.rvm/gems/ruby-2.2.4@os-bifrost/gems/azure-0.7.6/lib/azure/service_bus/auth/shared_access_signer.rb:28:in `token'
	/Users/cake/.rvm/gems/ruby-2.2.4@os-bifrost/gems/azure-0.7.6/lib/azure/service_bus/auth/shared_access_signer.rb:33:in `sign_request'
	/Users/cake/.rvm/gems/ruby-2.2.4@os-bifrost/gems/azure-core-0.1.5/lib/azure/core/http/signer_filter.rb:27:in `call'
	/Users/cake/.rvm/gems/ruby-2.2.4@os-bifrost/gems/azure-core-0.1.5/lib/azure/core/http/http_request.rb:104:in `block in with_filter'
	/Users/cake/.rvm/gems/ruby-2.2.4@os-bifrost/gems/azure-core-0.1.5/lib/azure/core/service.rb:36:in `call'
	/Users/cake/.rvm/gems/ruby-2.2.4@os-bifrost/gems/azure-core-0.1.5/lib/azure/core/filtered_service.rb:34:in `call'
	/Users/cake/.rvm/gems/ruby-2.2.4@os-bifrost/gems/azure-core-0.1.5/lib/azure/core/signed_service.rb:41:in `call'
	/Users/cake/.rvm/gems/ruby-2.2.4@os-bifrost/gems/azure-0.7.6/lib/azure/service_bus/service_bus_service.rb:662:in `_retrieve_message'
	/Users/cake/.rvm/gems/ruby-2.2.4@os-bifrost/gems/azure-0.7.6/lib/azure/service_bus/service_bus_service.rb:656:in `_peek_lock_message'
	/Users/cake/.rvm/gems/ruby-2.2.4@os-bifrost/gems/azure-0.7.6/lib/azure/service_bus/service_bus_service.rb:424:in `peek_lock_subscription_message'
	/Users/cake/.rvm/gems/ruby-2.2.4@os-bifrost/gems/azure-0.7.6/lib/azure/service_bus/service_bus_service.rb:601:in `receive_subscription_message'
	/Users/cake/Documents/open_source/bifrost/lib/bifrost/worker.rb:58:in `read_message'
	/Users/cake/Documents/open_source/bifrost/lib/bifrost/worker.rb:33:in `block in run'
	/Users/cake/Documents/open_source/bifrost/lib/bifrost/worker.rb:32:in `loop'
	/Users/cake/Documents/open_source/bifrost/lib/bifrost/worker.rb:32:in `run'
	/Users/cake/.rvm/gems/ruby-2.2.4@os-bifrost/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
	/Users/cake/.rvm/gems/ruby-2.2.4@os-bifrost/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
	/Users/cake/.rvm/gems/ruby-2.2.4@os-bifrost/gems/celluloid-0.17.3/lib/celluloid/call/async.rb:7:in `dispatch'
	/Users/cake/.rvm/gems/ruby-2.2.4@os-bifrost/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
	/Users/cake/.rvm/gems/ruby-2.2.4@os-bifrost/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
	/Users/cake/.rvm/gems/ruby-2.2.4@os-bifrost/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
	/Users/cake/.rvm/gems/ruby-2.2.4@os-bifrost/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
	/Users/cake/.rvm/gems/ruby-2.2.4@os-bifrost/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
```

**Comment by lfportal** [comment]
The errors appeared because I hadn't loaded the environment variables in my console session.
